// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { appControllerGetHello, authControllerGoogleAuth, authControllerGoogleAuthRedirect, type Options, ragControllerGetFiles, ragControllerIngest } from '../sdk.gen';
import type { AppControllerGetHelloData, AuthControllerGoogleAuthData, AuthControllerGoogleAuthRedirectData, RagControllerGetFilesData, RagControllerGetFilesResponse, RagControllerIngestData } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const appControllerGetHelloQueryKey = (options?: Options<AppControllerGetHelloData>) => createQueryKey('appControllerGetHello', options);

export const appControllerGetHelloOptions = (options?: Options<AppControllerGetHelloData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof appControllerGetHelloQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await appControllerGetHello({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: appControllerGetHelloQueryKey(options)
});

export const ragControllerGetFilesQueryKey = (options?: Options<RagControllerGetFilesData>) => createQueryKey('ragControllerGetFiles', options);

export const ragControllerGetFilesOptions = (options?: Options<RagControllerGetFilesData>) => queryOptions<RagControllerGetFilesResponse, DefaultError, RagControllerGetFilesResponse, ReturnType<typeof ragControllerGetFilesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ragControllerGetFiles({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: ragControllerGetFilesQueryKey(options)
});

export const ragControllerIngestMutation = (options?: Partial<Options<RagControllerIngestData>>): UseMutationOptions<unknown, DefaultError, Options<RagControllerIngestData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<RagControllerIngestData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ragControllerIngest({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const authControllerGoogleAuthQueryKey = (options?: Options<AuthControllerGoogleAuthData>) => createQueryKey('authControllerGoogleAuth', options);

export const authControllerGoogleAuthOptions = (options?: Options<AuthControllerGoogleAuthData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof authControllerGoogleAuthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await authControllerGoogleAuth({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: authControllerGoogleAuthQueryKey(options)
});

export const authControllerGoogleAuthRedirectQueryKey = (options?: Options<AuthControllerGoogleAuthRedirectData>) => createQueryKey('authControllerGoogleAuthRedirect', options);

export const authControllerGoogleAuthRedirectOptions = (options?: Options<AuthControllerGoogleAuthRedirectData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof authControllerGoogleAuthRedirectQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await authControllerGoogleAuthRedirect({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: authControllerGoogleAuthRedirectQueryKey(options)
});
