// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { appControllerGetHello, authControllerGoogleAuth, authControllerLogout, authControllerMe, authControllerRefresh, chatControllerClearHistory, chatControllerDeleteMessage, chatControllerGetChatHistory, chatControllerGetMessage, chatControllerQuery, type Options, ragControllerDeleteFile, ragControllerGetFile, ragControllerGetFiles, ragControllerIngest, workspacesControllerCreate, workspacesControllerFindAll, workspacesControllerFindOne, workspacesControllerRemove, workspacesControllerUpdate } from '../sdk.gen';
import type { AppControllerGetHelloData, AuthControllerGoogleAuthData, AuthControllerLogoutData, AuthControllerLogoutResponse, AuthControllerMeData, AuthControllerMeResponse, AuthControllerRefreshData, AuthControllerRefreshResponse, ChatControllerClearHistoryData, ChatControllerDeleteMessageData, ChatControllerGetChatHistoryData, ChatControllerGetChatHistoryResponse, ChatControllerGetMessageData, ChatControllerGetMessageResponse, ChatControllerQueryData, ChatControllerQueryResponse, RagControllerDeleteFileData, RagControllerGetFileData, RagControllerGetFileResponse, RagControllerGetFilesData, RagControllerGetFilesResponse, RagControllerIngestData, RagControllerIngestResponse, WorkspacesControllerCreateData, WorkspacesControllerCreateResponse, WorkspacesControllerFindAllData, WorkspacesControllerFindAllResponse, WorkspacesControllerFindOneData, WorkspacesControllerFindOneResponse, WorkspacesControllerRemoveData, WorkspacesControllerUpdateData, WorkspacesControllerUpdateResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const appControllerGetHelloQueryKey = (options?: Options<AppControllerGetHelloData>) => createQueryKey('appControllerGetHello', options);

export const appControllerGetHelloOptions = (options?: Options<AppControllerGetHelloData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof appControllerGetHelloQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await appControllerGetHello({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: appControllerGetHelloQueryKey(options)
});

export const ragControllerGetFilesQueryKey = (options: Options<RagControllerGetFilesData>) => createQueryKey('ragControllerGetFiles', options);

/**
 * Get all files in a workspace
 */
export const ragControllerGetFilesOptions = (options: Options<RagControllerGetFilesData>) => queryOptions<RagControllerGetFilesResponse, DefaultError, RagControllerGetFilesResponse, ReturnType<typeof ragControllerGetFilesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ragControllerGetFiles({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: ragControllerGetFilesQueryKey(options)
});

/**
 * Upload and ingest a PDF file
 */
export const ragControllerIngestMutation = (options?: Partial<Options<RagControllerIngestData>>): UseMutationOptions<RagControllerIngestResponse, DefaultError, Options<RagControllerIngestData>> => {
    const mutationOptions: UseMutationOptions<RagControllerIngestResponse, DefaultError, Options<RagControllerIngestData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ragControllerIngest({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete a file
 */
export const ragControllerDeleteFileMutation = (options?: Partial<Options<RagControllerDeleteFileData>>): UseMutationOptions<unknown, DefaultError, Options<RagControllerDeleteFileData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<RagControllerDeleteFileData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ragControllerDeleteFile({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const ragControllerGetFileQueryKey = (options: Options<RagControllerGetFileData>) => createQueryKey('ragControllerGetFile', options);

/**
 * Get a specific file by ID
 */
export const ragControllerGetFileOptions = (options: Options<RagControllerGetFileData>) => queryOptions<RagControllerGetFileResponse, DefaultError, RagControllerGetFileResponse, ReturnType<typeof ragControllerGetFileQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ragControllerGetFile({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: ragControllerGetFileQueryKey(options)
});

export const workspacesControllerFindAllQueryKey = (options?: Options<WorkspacesControllerFindAllData>) => createQueryKey('workspacesControllerFindAll', options);

/**
 * Get all workspaces for the current user
 */
export const workspacesControllerFindAllOptions = (options?: Options<WorkspacesControllerFindAllData>) => queryOptions<WorkspacesControllerFindAllResponse, DefaultError, WorkspacesControllerFindAllResponse, ReturnType<typeof workspacesControllerFindAllQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await workspacesControllerFindAll({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: workspacesControllerFindAllQueryKey(options)
});

/**
 * Create a new workspace
 */
export const workspacesControllerCreateMutation = (options?: Partial<Options<WorkspacesControllerCreateData>>): UseMutationOptions<WorkspacesControllerCreateResponse, DefaultError, Options<WorkspacesControllerCreateData>> => {
    const mutationOptions: UseMutationOptions<WorkspacesControllerCreateResponse, DefaultError, Options<WorkspacesControllerCreateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await workspacesControllerCreate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete a workspace
 */
export const workspacesControllerRemoveMutation = (options?: Partial<Options<WorkspacesControllerRemoveData>>): UseMutationOptions<unknown, DefaultError, Options<WorkspacesControllerRemoveData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<WorkspacesControllerRemoveData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await workspacesControllerRemove({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const workspacesControllerFindOneQueryKey = (options: Options<WorkspacesControllerFindOneData>) => createQueryKey('workspacesControllerFindOne', options);

/**
 * Get a specific workspace by ID
 */
export const workspacesControllerFindOneOptions = (options: Options<WorkspacesControllerFindOneData>) => queryOptions<WorkspacesControllerFindOneResponse, DefaultError, WorkspacesControllerFindOneResponse, ReturnType<typeof workspacesControllerFindOneQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await workspacesControllerFindOne({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: workspacesControllerFindOneQueryKey(options)
});

/**
 * Update a workspace
 */
export const workspacesControllerUpdateMutation = (options?: Partial<Options<WorkspacesControllerUpdateData>>): UseMutationOptions<WorkspacesControllerUpdateResponse, DefaultError, Options<WorkspacesControllerUpdateData>> => {
    const mutationOptions: UseMutationOptions<WorkspacesControllerUpdateResponse, DefaultError, Options<WorkspacesControllerUpdateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await workspacesControllerUpdate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const authControllerGoogleAuthQueryKey = (options?: Options<AuthControllerGoogleAuthData>) => createQueryKey('authControllerGoogleAuth', options);

/**
 * Initiate Google OAuth login
 */
export const authControllerGoogleAuthOptions = (options?: Options<AuthControllerGoogleAuthData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof authControllerGoogleAuthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await authControllerGoogleAuth({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: authControllerGoogleAuthQueryKey(options)
});

export const authControllerMeQueryKey = (options?: Options<AuthControllerMeData>) => createQueryKey('authControllerMe', options);

/**
 * Get current authenticated user
 */
export const authControllerMeOptions = (options?: Options<AuthControllerMeData>) => queryOptions<AuthControllerMeResponse, DefaultError, AuthControllerMeResponse, ReturnType<typeof authControllerMeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await authControllerMe({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: authControllerMeQueryKey(options)
});

/**
 * Refresh access token using refresh token cookie
 */
export const authControllerRefreshMutation = (options?: Partial<Options<AuthControllerRefreshData>>): UseMutationOptions<AuthControllerRefreshResponse, DefaultError, Options<AuthControllerRefreshData>> => {
    const mutationOptions: UseMutationOptions<AuthControllerRefreshResponse, DefaultError, Options<AuthControllerRefreshData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await authControllerRefresh({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Logout and clear auth cookies
 */
export const authControllerLogoutMutation = (options?: Partial<Options<AuthControllerLogoutData>>): UseMutationOptions<AuthControllerLogoutResponse, DefaultError, Options<AuthControllerLogoutData>> => {
    const mutationOptions: UseMutationOptions<AuthControllerLogoutResponse, DefaultError, Options<AuthControllerLogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await authControllerLogout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Ask a question about the documents in a workspace
 */
export const chatControllerQueryMutation = (options?: Partial<Options<ChatControllerQueryData>>): UseMutationOptions<ChatControllerQueryResponse, DefaultError, Options<ChatControllerQueryData>> => {
    const mutationOptions: UseMutationOptions<ChatControllerQueryResponse, DefaultError, Options<ChatControllerQueryData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await chatControllerQuery({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Clear all chat history for a workspace
 */
export const chatControllerClearHistoryMutation = (options?: Partial<Options<ChatControllerClearHistoryData>>): UseMutationOptions<unknown, DefaultError, Options<ChatControllerClearHistoryData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<ChatControllerClearHistoryData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await chatControllerClearHistory({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const chatControllerGetChatHistoryQueryKey = (options: Options<ChatControllerGetChatHistoryData>) => createQueryKey('chatControllerGetChatHistory', options);

/**
 * Get chat history for a workspace
 */
export const chatControllerGetChatHistoryOptions = (options: Options<ChatControllerGetChatHistoryData>) => queryOptions<ChatControllerGetChatHistoryResponse, DefaultError, ChatControllerGetChatHistoryResponse, ReturnType<typeof chatControllerGetChatHistoryQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await chatControllerGetChatHistory({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: chatControllerGetChatHistoryQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const chatControllerGetChatHistoryInfiniteQueryKey = (options: Options<ChatControllerGetChatHistoryData>): QueryKey<Options<ChatControllerGetChatHistoryData>> => createQueryKey('chatControllerGetChatHistory', options, true);

/**
 * Get chat history for a workspace
 */
export const chatControllerGetChatHistoryInfiniteOptions = (options: Options<ChatControllerGetChatHistoryData>) => infiniteQueryOptions<ChatControllerGetChatHistoryResponse, DefaultError, InfiniteData<ChatControllerGetChatHistoryResponse>, QueryKey<Options<ChatControllerGetChatHistoryData>>, number | Pick<QueryKey<Options<ChatControllerGetChatHistoryData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<ChatControllerGetChatHistoryData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                offset: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await chatControllerGetChatHistory({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: chatControllerGetChatHistoryInfiniteQueryKey(options)
});

/**
 * Delete a specific chat message
 */
export const chatControllerDeleteMessageMutation = (options?: Partial<Options<ChatControllerDeleteMessageData>>): UseMutationOptions<unknown, DefaultError, Options<ChatControllerDeleteMessageData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<ChatControllerDeleteMessageData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await chatControllerDeleteMessage({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const chatControllerGetMessageQueryKey = (options: Options<ChatControllerGetMessageData>) => createQueryKey('chatControllerGetMessage', options);

/**
 * Get a specific chat message
 */
export const chatControllerGetMessageOptions = (options: Options<ChatControllerGetMessageData>) => queryOptions<ChatControllerGetMessageResponse, DefaultError, ChatControllerGetMessageResponse, ReturnType<typeof chatControllerGetMessageQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await chatControllerGetMessage({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: chatControllerGetMessageQueryKey(options)
});
