// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { authControllerGoogleAuth, authControllerLogout, authControllerMe, authControllerRefresh, conversationsControllerDeleteMessage, conversationsControllerGetMessages, documentsControllerDeleteFile, documentsControllerGetFile, documentsControllerGetFiles, documentsControllerIngest, flashcardsControllerCreate, flashcardsControllerFindAll, flashcardsControllerFindOne, flashcardsControllerGenerate, flashcardsControllerRemove, flashcardsControllerUpdate, knowledgeHubsControllerCreate, knowledgeHubsControllerFindAll, knowledgeHubsControllerFindOne, knowledgeHubsControllerRemove, knowledgeHubsControllerUpdate, notesControllerCreate, notesControllerFindAll, notesControllerFindOne, notesControllerGenerate, notesControllerRemove, notesControllerUpdate, type Options, queryControllerQuery } from '../sdk.gen';
import type { AuthControllerGoogleAuthData, AuthControllerLogoutData, AuthControllerLogoutResponse, AuthControllerMeData, AuthControllerMeResponse, AuthControllerRefreshData, AuthControllerRefreshResponse, ConversationsControllerDeleteMessageData, ConversationsControllerGetMessagesData, ConversationsControllerGetMessagesResponse, DocumentsControllerDeleteFileData, DocumentsControllerGetFileData, DocumentsControllerGetFileResponse, DocumentsControllerGetFilesData, DocumentsControllerGetFilesResponse, DocumentsControllerIngestData, DocumentsControllerIngestResponse, FlashcardsControllerCreateData, FlashcardsControllerFindAllData, FlashcardsControllerFindOneData, FlashcardsControllerGenerateData, FlashcardsControllerRemoveData, FlashcardsControllerUpdateData, KnowledgeHubsControllerCreateData, KnowledgeHubsControllerCreateResponse, KnowledgeHubsControllerFindAllData, KnowledgeHubsControllerFindAllResponse, KnowledgeHubsControllerFindOneData, KnowledgeHubsControllerFindOneResponse, KnowledgeHubsControllerRemoveData, KnowledgeHubsControllerUpdateData, KnowledgeHubsControllerUpdateResponse, NotesControllerCreateData, NotesControllerFindAllData, NotesControllerFindOneData, NotesControllerGenerateData, NotesControllerRemoveData, NotesControllerUpdateData, QueryControllerQueryData, QueryControllerQueryResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const documentsControllerGetFilesQueryKey = (options: Options<DocumentsControllerGetFilesData>) => createQueryKey('documentsControllerGetFiles', options);

/**
 * Get all documents in a knowledge hub
 */
export const documentsControllerGetFilesOptions = (options: Options<DocumentsControllerGetFilesData>) => queryOptions<DocumentsControllerGetFilesResponse, DefaultError, DocumentsControllerGetFilesResponse, ReturnType<typeof documentsControllerGetFilesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await documentsControllerGetFiles({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: documentsControllerGetFilesQueryKey(options)
});

/**
 * Upload and ingest a PDF document
 */
export const documentsControllerIngestMutation = (options?: Partial<Options<DocumentsControllerIngestData>>): UseMutationOptions<DocumentsControllerIngestResponse, DefaultError, Options<DocumentsControllerIngestData>> => {
    const mutationOptions: UseMutationOptions<DocumentsControllerIngestResponse, DefaultError, Options<DocumentsControllerIngestData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await documentsControllerIngest({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete a document
 */
export const documentsControllerDeleteFileMutation = (options?: Partial<Options<DocumentsControllerDeleteFileData>>): UseMutationOptions<unknown, DefaultError, Options<DocumentsControllerDeleteFileData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<DocumentsControllerDeleteFileData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await documentsControllerDeleteFile({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const documentsControllerGetFileQueryKey = (options: Options<DocumentsControllerGetFileData>) => createQueryKey('documentsControllerGetFile', options);

/**
 * Get a specific document by ID
 */
export const documentsControllerGetFileOptions = (options: Options<DocumentsControllerGetFileData>) => queryOptions<DocumentsControllerGetFileResponse, DefaultError, DocumentsControllerGetFileResponse, ReturnType<typeof documentsControllerGetFileQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await documentsControllerGetFile({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: documentsControllerGetFileQueryKey(options)
});

export const knowledgeHubsControllerFindAllQueryKey = (options?: Options<KnowledgeHubsControllerFindAllData>) => createQueryKey('knowledgeHubsControllerFindAll', options);

/**
 * Get all knowledge hubs for the current user
 */
export const knowledgeHubsControllerFindAllOptions = (options?: Options<KnowledgeHubsControllerFindAllData>) => queryOptions<KnowledgeHubsControllerFindAllResponse, DefaultError, KnowledgeHubsControllerFindAllResponse, ReturnType<typeof knowledgeHubsControllerFindAllQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await knowledgeHubsControllerFindAll({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: knowledgeHubsControllerFindAllQueryKey(options)
});

/**
 * Create a new knowledge hub
 */
export const knowledgeHubsControllerCreateMutation = (options?: Partial<Options<KnowledgeHubsControllerCreateData>>): UseMutationOptions<KnowledgeHubsControllerCreateResponse, DefaultError, Options<KnowledgeHubsControllerCreateData>> => {
    const mutationOptions: UseMutationOptions<KnowledgeHubsControllerCreateResponse, DefaultError, Options<KnowledgeHubsControllerCreateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await knowledgeHubsControllerCreate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete a knowledge hub
 */
export const knowledgeHubsControllerRemoveMutation = (options?: Partial<Options<KnowledgeHubsControllerRemoveData>>): UseMutationOptions<unknown, DefaultError, Options<KnowledgeHubsControllerRemoveData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<KnowledgeHubsControllerRemoveData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await knowledgeHubsControllerRemove({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const knowledgeHubsControllerFindOneQueryKey = (options: Options<KnowledgeHubsControllerFindOneData>) => createQueryKey('knowledgeHubsControllerFindOne', options);

/**
 * Get a specific knowledge hub by ID
 */
export const knowledgeHubsControllerFindOneOptions = (options: Options<KnowledgeHubsControllerFindOneData>) => queryOptions<KnowledgeHubsControllerFindOneResponse, DefaultError, KnowledgeHubsControllerFindOneResponse, ReturnType<typeof knowledgeHubsControllerFindOneQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await knowledgeHubsControllerFindOne({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: knowledgeHubsControllerFindOneQueryKey(options)
});

/**
 * Update a knowledge hub
 */
export const knowledgeHubsControllerUpdateMutation = (options?: Partial<Options<KnowledgeHubsControllerUpdateData>>): UseMutationOptions<KnowledgeHubsControllerUpdateResponse, DefaultError, Options<KnowledgeHubsControllerUpdateData>> => {
    const mutationOptions: UseMutationOptions<KnowledgeHubsControllerUpdateResponse, DefaultError, Options<KnowledgeHubsControllerUpdateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await knowledgeHubsControllerUpdate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const authControllerGoogleAuthQueryKey = (options?: Options<AuthControllerGoogleAuthData>) => createQueryKey('authControllerGoogleAuth', options);

/**
 * Initiate Google OAuth login
 */
export const authControllerGoogleAuthOptions = (options?: Options<AuthControllerGoogleAuthData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof authControllerGoogleAuthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await authControllerGoogleAuth({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: authControllerGoogleAuthQueryKey(options)
});

export const authControllerMeQueryKey = (options?: Options<AuthControllerMeData>) => createQueryKey('authControllerMe', options);

/**
 * Get current authenticated user
 */
export const authControllerMeOptions = (options?: Options<AuthControllerMeData>) => queryOptions<AuthControllerMeResponse, DefaultError, AuthControllerMeResponse, ReturnType<typeof authControllerMeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await authControllerMe({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: authControllerMeQueryKey(options)
});

/**
 * Refresh access token using refresh token cookie
 */
export const authControllerRefreshMutation = (options?: Partial<Options<AuthControllerRefreshData>>): UseMutationOptions<AuthControllerRefreshResponse, DefaultError, Options<AuthControllerRefreshData>> => {
    const mutationOptions: UseMutationOptions<AuthControllerRefreshResponse, DefaultError, Options<AuthControllerRefreshData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await authControllerRefresh({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Logout and clear auth cookies
 */
export const authControllerLogoutMutation = (options?: Partial<Options<AuthControllerLogoutData>>): UseMutationOptions<AuthControllerLogoutResponse, DefaultError, Options<AuthControllerLogoutData>> => {
    const mutationOptions: UseMutationOptions<AuthControllerLogoutResponse, DefaultError, Options<AuthControllerLogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await authControllerLogout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Ask a question about the documents in a knowledge hub
 *
 * Asks a question in the single chat thread for this knowledge hub and returns an answer with sources.
 */
export const queryControllerQueryMutation = (options?: Partial<Options<QueryControllerQueryData>>): UseMutationOptions<QueryControllerQueryResponse, DefaultError, Options<QueryControllerQueryData>> => {
    const mutationOptions: UseMutationOptions<QueryControllerQueryResponse, DefaultError, Options<QueryControllerQueryData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await queryControllerQuery({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const conversationsControllerGetMessagesQueryKey = (options: Options<ConversationsControllerGetMessagesData>) => createQueryKey('conversationsControllerGetMessages', options);

/**
 * Get all messages in the knowledge hub chat thread
 */
export const conversationsControllerGetMessagesOptions = (options: Options<ConversationsControllerGetMessagesData>) => queryOptions<ConversationsControllerGetMessagesResponse, DefaultError, ConversationsControllerGetMessagesResponse, ReturnType<typeof conversationsControllerGetMessagesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await conversationsControllerGetMessages({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: conversationsControllerGetMessagesQueryKey(options)
});

/**
 * Delete a specific message from knowledge hub thread
 */
export const conversationsControllerDeleteMessageMutation = (options?: Partial<Options<ConversationsControllerDeleteMessageData>>): UseMutationOptions<unknown, DefaultError, Options<ConversationsControllerDeleteMessageData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<ConversationsControllerDeleteMessageData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await conversationsControllerDeleteMessage({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const notesControllerFindAllQueryKey = (options: Options<NotesControllerFindAllData>) => createQueryKey('notesControllerFindAll', options);

/**
 * List notes in a knowledge hub
 */
export const notesControllerFindAllOptions = (options: Options<NotesControllerFindAllData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof notesControllerFindAllQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await notesControllerFindAll({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: notesControllerFindAllQueryKey(options)
});

/**
 * Create a manual note
 */
export const notesControllerCreateMutation = (options?: Partial<Options<NotesControllerCreateData>>): UseMutationOptions<unknown, DefaultError, Options<NotesControllerCreateData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<NotesControllerCreateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await notesControllerCreate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete a note
 */
export const notesControllerRemoveMutation = (options?: Partial<Options<NotesControllerRemoveData>>): UseMutationOptions<unknown, DefaultError, Options<NotesControllerRemoveData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<NotesControllerRemoveData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await notesControllerRemove({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const notesControllerFindOneQueryKey = (options: Options<NotesControllerFindOneData>) => createQueryKey('notesControllerFindOne', options);

/**
 * Get a note by ID
 */
export const notesControllerFindOneOptions = (options: Options<NotesControllerFindOneData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof notesControllerFindOneQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await notesControllerFindOne({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: notesControllerFindOneQueryKey(options)
});

/**
 * Update a note
 */
export const notesControllerUpdateMutation = (options?: Partial<Options<NotesControllerUpdateData>>): UseMutationOptions<unknown, DefaultError, Options<NotesControllerUpdateData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<NotesControllerUpdateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await notesControllerUpdate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Generate a note from contextual input
 */
export const notesControllerGenerateMutation = (options?: Partial<Options<NotesControllerGenerateData>>): UseMutationOptions<unknown, DefaultError, Options<NotesControllerGenerateData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<NotesControllerGenerateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await notesControllerGenerate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const flashcardsControllerFindAllQueryKey = (options: Options<FlashcardsControllerFindAllData>) => createQueryKey('flashcardsControllerFindAll', options);

/**
 * List flashcards in a knowledge hub
 */
export const flashcardsControllerFindAllOptions = (options: Options<FlashcardsControllerFindAllData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof flashcardsControllerFindAllQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await flashcardsControllerFindAll({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: flashcardsControllerFindAllQueryKey(options)
});

/**
 * Create a manual flashcard
 */
export const flashcardsControllerCreateMutation = (options?: Partial<Options<FlashcardsControllerCreateData>>): UseMutationOptions<unknown, DefaultError, Options<FlashcardsControllerCreateData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<FlashcardsControllerCreateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await flashcardsControllerCreate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete a flashcard
 */
export const flashcardsControllerRemoveMutation = (options?: Partial<Options<FlashcardsControllerRemoveData>>): UseMutationOptions<unknown, DefaultError, Options<FlashcardsControllerRemoveData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<FlashcardsControllerRemoveData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await flashcardsControllerRemove({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const flashcardsControllerFindOneQueryKey = (options: Options<FlashcardsControllerFindOneData>) => createQueryKey('flashcardsControllerFindOne', options);

/**
 * Get a flashcard by ID
 */
export const flashcardsControllerFindOneOptions = (options: Options<FlashcardsControllerFindOneData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof flashcardsControllerFindOneQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await flashcardsControllerFindOne({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: flashcardsControllerFindOneQueryKey(options)
});

/**
 * Update a flashcard
 */
export const flashcardsControllerUpdateMutation = (options?: Partial<Options<FlashcardsControllerUpdateData>>): UseMutationOptions<unknown, DefaultError, Options<FlashcardsControllerUpdateData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<FlashcardsControllerUpdateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await flashcardsControllerUpdate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Generate flashcards from contextual input
 */
export const flashcardsControllerGenerateMutation = (options?: Partial<Options<FlashcardsControllerGenerateData>>): UseMutationOptions<unknown, DefaultError, Options<FlashcardsControllerGenerateData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<FlashcardsControllerGenerateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await flashcardsControllerGenerate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
