// This file is auto-generated by @hey-api/openapi-ts

export const FileResponseDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            description: 'File ID'
        },
        name: {
            type: 'string',
            description: 'File name'
        },
        originalName: {
            type: 'string',
            description: 'Original file name'
        },
        mimeType: {
            type: 'string',
            description: 'MIME type of the file'
        },
        size: {
            type: 'number',
            description: 'File size in bytes'
        },
        status: {
            type: 'string',
            description: 'Processing status',
            enum: [
                'pending',
                'processing',
                'completed',
                'failed'
            ],
            example: 'pending'
        },
        errorMessage: {
            type: 'string',
            description: 'Error message if processing failed'
        },
        knowledgeHubId: {
            type: 'string',
            description: 'Knowledge hub ID this file belongs to'
        },
        createdAt: {
            format: 'date-time',
            type: 'string',
            description: 'Created timestamp'
        },
        updatedAt: {
            format: 'date-time',
            type: 'string',
            description: 'Updated timestamp'
        }
    },
    required: [
        'id',
        'name',
        'originalName',
        'mimeType',
        'size',
        'status',
        'knowledgeHubId',
        'createdAt',
        'updatedAt'
    ]
} as const;

export const IngestResponseDtoSchema = {
    type: 'object',
    properties: {
        message: {
            type: 'string',
            description: 'Status message'
        },
        fileId: {
            type: 'string',
            description: 'File ID'
        },
        status: {
            type: 'string',
            description: 'Current processing status',
            enum: [
                'pending',
                'processing',
                'completed',
                'failed'
            ],
            example: 'processing'
        }
    },
    required: [
        'message',
        'fileId',
        'status'
    ]
} as const;

export const CreateKnowledgeHubDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            description: 'Name of the knowledge hub',
            example: 'Product Architecture',
            maxLength: 255
        },
        description: {
            type: 'string',
            description: 'Optional description of the knowledge hub',
            example: 'All docs, notes, chat, and cards for the product architecture'
        }
    },
    required: [
        'name'
    ]
} as const;

export const KnowledgeHubResponseDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            description: 'Unique identifier of the knowledge hub',
            example: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890'
        },
        name: {
            type: 'string',
            description: 'Name of the knowledge hub',
            example: 'Product Architecture'
        },
        description: {
            type: 'object',
            description: 'Description of the knowledge hub',
            nullable: true
        },
        ownerId: {
            type: 'string',
            description: 'ID of the knowledge hub owner'
        },
        createdAt: {
            format: 'date-time',
            type: 'string',
            description: 'Creation timestamp'
        },
        updatedAt: {
            format: 'date-time',
            type: 'string',
            description: 'Last update timestamp'
        }
    },
    required: [
        'id',
        'name',
        'description',
        'ownerId',
        'createdAt',
        'updatedAt'
    ]
} as const;

export const UpdateKnowledgeHubDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            description: 'Name of the knowledge hub',
            example: 'Updated Product Architecture',
            maxLength: 255
        },
        description: {
            type: 'string',
            description: 'Optional description of the knowledge hub',
            example: 'Updated description'
        }
    }
} as const;

export const UserResponseDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            description: 'Unique identifier of the user',
            example: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890'
        },
        email: {
            type: 'string',
            description: 'Email address of the user',
            example: 'user@example.com'
        },
        firstName: {
            type: 'object',
            description: 'First name of the user',
            example: 'John',
            nullable: true
        },
        lastName: {
            type: 'object',
            description: 'Last name of the user',
            example: 'Doe',
            nullable: true
        },
        picture: {
            type: 'object',
            description: 'Profile picture URL',
            example: 'https://example.com/photo.jpg',
            nullable: true
        },
        isAdmin: {
            type: 'boolean',
            description: 'Whether the user has admin privileges',
            example: false
        }
    },
    required: [
        'id',
        'email',
        'firstName',
        'lastName',
        'picture',
        'isAdmin'
    ]
} as const;

export const RefreshResponseDtoSchema = {
    type: 'object',
    properties: {
        ok: {
            type: 'boolean',
            description: 'Indicates the refresh was successful',
            example: true
        }
    },
    required: [
        'ok'
    ]
} as const;

export const LogoutResponseDtoSchema = {
    type: 'object',
    properties: {
        ok: {
            type: 'boolean',
            description: 'Indicates the logout was successful',
            example: true
        }
    },
    required: [
        'ok'
    ]
} as const;

export const QueryInConversationDtoSchema = {
    type: 'object',
    properties: {
        question: {
            type: 'string',
            description: 'The question to ask about the documents',
            example: 'What is the main topic of the document?',
            minLength: 3,
            maxLength: 1000
        },
        conversationId: {
            type: 'string',
            description: 'ID of an existing conversation to continue. If not provided, a new conversation will be created.',
            example: '123e4567-e89b-12d3-a456-426614174000'
        }
    },
    required: [
        'question'
    ]
} as const;

export const QueryInConversationResponseDtoSchema = {
    type: 'object',
    properties: {
        answer: {
            type: 'string',
            description: 'The AI-generated answer'
        },
        sources: {
            type: 'array',
            description: 'Source documents used to generate the answer',
            items: {
                type: 'object',
                properties: {
                    fileId: {
                        type: 'string'
                    },
                    text: {
                        type: 'string'
                    },
                    score: {
                        type: 'number'
                    }
                }
            }
        },
        conversationId: {
            type: 'string',
            description: 'The conversation ID (new or existing)'
        },
        messageId: {
            type: 'string',
            description: 'The message ID of this Q&A'
        }
    },
    required: [
        'answer',
        'sources',
        'conversationId',
        'messageId'
    ]
} as const;

export const ChatMessageSourceDtoSchema = {
    type: 'object',
    properties: {
        fileId: {
            type: 'string',
            description: 'The file ID this source belongs to'
        },
        text: {
            type: 'string',
            description: 'The text content of the source'
        },
        score: {
            type: 'number',
            description: 'Similarity score (0-1)'
        }
    },
    required: [
        'fileId',
        'text',
        'score'
    ]
} as const;

export const ChatMessageResponseDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            description: 'Unique identifier of the chat message'
        },
        question: {
            type: 'string',
            description: 'The question asked by the user'
        },
        answer: {
            type: 'string',
            description: 'The AI-generated answer'
        },
        sources: {
            description: 'Source documents used to generate the answer',
            nullable: true,
            type: 'array',
            items: {
                $ref: '#/components/schemas/ChatMessageSourceDto'
            }
        },
        threadId: {
            type: 'string',
            description: 'ID of the thread this message belongs to'
        },
        userId: {
            type: 'string',
            description: 'ID of the user who asked the question'
        },
        createdAt: {
            format: 'date-time',
            type: 'string',
            description: 'When the message was created'
        }
    },
    required: [
        'id',
        'question',
        'answer',
        'sources',
        'threadId',
        'userId',
        'createdAt'
    ]
} as const;

export const CreateNoteDtoSchema = {
    type: 'object',
    properties: {
        title: {
            type: 'string',
            description: 'Note title',
            example: 'Q3 rollout checklist',
            maxLength: 255
        },
        content: {
            type: 'string',
            description: 'Note content in plain text or markdown',
            example: 'Key points from today\'s review...'
        }
    },
    required: [
        'title',
        'content'
    ]
} as const;

export const UpdateNoteDtoSchema = {
    type: 'object',
    properties: {
        title: {
            type: 'string',
            description: 'Note title',
            example: 'Q3 rollout checklist (updated)',
            maxLength: 255
        },
        content: {
            type: 'string',
            description: 'Note content in plain text or markdown',
            example: 'Updated notes after reviewing action items.'
        }
    }
} as const;

export const GenerateNoteDtoSchema = {
    type: 'object',
    properties: {
        mode: {
            type: 'string',
            description: 'How the note should be generated',
            enum: [
                'from_answer',
                'from_selection',
                'from_topic_query'
            ],
            example: 'from_answer'
        },
        query: {
            type: 'string',
            description: 'Topic query text used when mode is from_topic_query',
            example: 'Summarize OAuth2 authorization code flow from uploaded docs',
            minLength: 3,
            maxLength: 4000
        },
        messageId: {
            type: 'string',
            description: 'Chat message ID used when mode is from_answer',
            example: '123e4567-e89b-12d3-a456-426614174000'
        },
        documentId: {
            type: 'string',
            description: 'Document ID used when mode is from_selection',
            example: '123e4567-e89b-12d3-a456-426614174000'
        },
        selectionText: {
            type: 'string',
            description: 'Selected text from document used when mode is from_selection',
            example: 'OAuth2 authorization code flow exchanges an auth code for access token.',
            minLength: 3,
            maxLength: 4000
        },
        title: {
            type: 'string',
            description: 'Optional note title override',
            example: 'Study Notes: API Authentication',
            maxLength: 255
        }
    },
    required: [
        'mode'
    ]
} as const;

export const CreateFlashcardDtoSchema = {
    type: 'object',
    properties: {
        front: {
            type: 'string',
            description: 'Flashcard front text (question/prompt)',
            example: 'What is retrieval augmented generation (RAG)?'
        },
        back: {
            type: 'string',
            description: 'Flashcard back text (answer/explanation)',
            example: 'A pattern that augments LLM prompts with retrieved context.'
        }
    },
    required: [
        'front',
        'back'
    ]
} as const;

export const UpdateFlashcardDtoSchema = {
    type: 'object',
    properties: {
        front: {
            type: 'string',
            description: 'Flashcard front text (question/prompt)',
            example: 'What does RAG stand for?'
        },
        back: {
            type: 'string',
            description: 'Flashcard back text (answer/explanation)',
            example: 'Retrieval Augmented Generation'
        }
    }
} as const;

export const GenerateFlashcardDtoSchema = {
    type: 'object',
    properties: {
        mode: {
            type: 'string',
            description: 'How the flashcards should be generated',
            enum: [
                'from_answer',
                'from_selection',
                'from_topic_query'
            ],
            example: 'from_topic_query'
        },
        query: {
            type: 'string',
            description: 'Topic query text used when mode is from_topic_query',
            example: 'Generate cards about OAuth2 authorization code flow.',
            maxLength: 4000
        },
        messageId: {
            type: 'string',
            description: 'Chat message ID used when mode is from_answer',
            example: '123e4567-e89b-12d3-a456-426614174000'
        },
        documentId: {
            type: 'string',
            description: 'Document ID used when mode is from_selection',
            example: '123e4567-e89b-12d3-a456-426614174000'
        },
        selectionText: {
            type: 'string',
            description: 'Selected text from document used when mode is from_selection',
            example: 'OAuth2 uses authorization code exchange for tokens.',
            maxLength: 4000
        },
        count: {
            type: 'number',
            description: 'Number of flashcards to generate',
            example: 5,
            minimum: 1,
            maximum: 20,
            default: 5
        }
    },
    required: [
        'mode'
    ]
} as const;
