// This file is auto-generated by @hey-api/openapi-ts

export const FileResponseDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        }
    },
    required: [
        'id',
        'name'
    ]
} as const;
