// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { AuthControllerGoogleAuthData, AuthControllerLogoutData, AuthControllerLogoutResponses, AuthControllerMeData, AuthControllerMeErrors, AuthControllerMeResponses, AuthControllerRefreshData, AuthControllerRefreshErrors, AuthControllerRefreshResponses, ChatMessagesControllerDeleteMessageData, ChatMessagesControllerDeleteMessageErrors, ChatMessagesControllerDeleteMessageResponses, ChatMessagesControllerGetMessagesData, ChatMessagesControllerGetMessagesErrors, ChatMessagesControllerGetMessagesResponses, DocumentsControllerDeleteFileData, DocumentsControllerDeleteFileResponses, DocumentsControllerGetFileData, DocumentsControllerGetFileResponses, DocumentsControllerGetFilesData, DocumentsControllerGetFilesResponses, DocumentsControllerIngestData, DocumentsControllerIngestResponses, KnowledgeHubsControllerCreateData, KnowledgeHubsControllerCreateErrors, KnowledgeHubsControllerCreateResponses, KnowledgeHubsControllerFindAllData, KnowledgeHubsControllerFindAllErrors, KnowledgeHubsControllerFindAllResponses, KnowledgeHubsControllerFindOneData, KnowledgeHubsControllerFindOneErrors, KnowledgeHubsControllerFindOneResponses, KnowledgeHubsControllerRemoveData, KnowledgeHubsControllerRemoveErrors, KnowledgeHubsControllerRemoveResponses, KnowledgeHubsControllerUpdateData, KnowledgeHubsControllerUpdateErrors, KnowledgeHubsControllerUpdateResponses, QueryControllerQueryData, QueryControllerQueryErrors, QueryControllerQueryResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get all documents in a knowledge hub
 */
export const documentsControllerGetFiles = <ThrowOnError extends boolean = false>(options: Options<DocumentsControllerGetFilesData, ThrowOnError>) => (options.client ?? client).get<DocumentsControllerGetFilesResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/knowledge-hubs/{hubId}/documents',
    ...options
});

/**
 * Upload and ingest a PDF document
 */
export const documentsControllerIngest = <ThrowOnError extends boolean = false>(options: Options<DocumentsControllerIngestData, ThrowOnError>) => (options.client ?? client).post<DocumentsControllerIngestResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/knowledge-hubs/{hubId}/documents',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Delete a document
 */
export const documentsControllerDeleteFile = <ThrowOnError extends boolean = false>(options: Options<DocumentsControllerDeleteFileData, ThrowOnError>) => (options.client ?? client).delete<DocumentsControllerDeleteFileResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/knowledge-hubs/{hubId}/documents/{fileId}',
    ...options
});

/**
 * Get a specific document by ID
 */
export const documentsControllerGetFile = <ThrowOnError extends boolean = false>(options: Options<DocumentsControllerGetFileData, ThrowOnError>) => (options.client ?? client).get<DocumentsControllerGetFileResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/knowledge-hubs/{hubId}/documents/{fileId}',
    ...options
});

/**
 * Get all knowledge hubs for the current user
 */
export const knowledgeHubsControllerFindAll = <ThrowOnError extends boolean = false>(options?: Options<KnowledgeHubsControllerFindAllData, ThrowOnError>) => (options?.client ?? client).get<KnowledgeHubsControllerFindAllResponses, KnowledgeHubsControllerFindAllErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/knowledge-hubs',
    ...options
});

/**
 * Create a new knowledge hub
 */
export const knowledgeHubsControllerCreate = <ThrowOnError extends boolean = false>(options: Options<KnowledgeHubsControllerCreateData, ThrowOnError>) => (options.client ?? client).post<KnowledgeHubsControllerCreateResponses, KnowledgeHubsControllerCreateErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/knowledge-hubs',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a knowledge hub
 */
export const knowledgeHubsControllerRemove = <ThrowOnError extends boolean = false>(options: Options<KnowledgeHubsControllerRemoveData, ThrowOnError>) => (options.client ?? client).delete<KnowledgeHubsControllerRemoveResponses, KnowledgeHubsControllerRemoveErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/knowledge-hubs/{id}',
    ...options
});

/**
 * Get a specific knowledge hub by ID
 */
export const knowledgeHubsControllerFindOne = <ThrowOnError extends boolean = false>(options: Options<KnowledgeHubsControllerFindOneData, ThrowOnError>) => (options.client ?? client).get<KnowledgeHubsControllerFindOneResponses, KnowledgeHubsControllerFindOneErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/knowledge-hubs/{id}',
    ...options
});

/**
 * Update a knowledge hub
 */
export const knowledgeHubsControllerUpdate = <ThrowOnError extends boolean = false>(options: Options<KnowledgeHubsControllerUpdateData, ThrowOnError>) => (options.client ?? client).patch<KnowledgeHubsControllerUpdateResponses, KnowledgeHubsControllerUpdateErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/knowledge-hubs/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Initiate Google OAuth login
 */
export const authControllerGoogleAuth = <ThrowOnError extends boolean = false>(options?: Options<AuthControllerGoogleAuthData, ThrowOnError>) => (options?.client ?? client).get<unknown, unknown, ThrowOnError>({ url: '/auth/google', ...options });

/**
 * Get current authenticated user
 */
export const authControllerMe = <ThrowOnError extends boolean = false>(options?: Options<AuthControllerMeData, ThrowOnError>) => (options?.client ?? client).get<AuthControllerMeResponses, AuthControllerMeErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/auth/me',
    ...options
});

/**
 * Refresh access token using refresh token cookie
 */
export const authControllerRefresh = <ThrowOnError extends boolean = false>(options?: Options<AuthControllerRefreshData, ThrowOnError>) => (options?.client ?? client).post<AuthControllerRefreshResponses, AuthControllerRefreshErrors, ThrowOnError>({ url: '/auth/refresh', ...options });

/**
 * Logout and clear auth cookies
 */
export const authControllerLogout = <ThrowOnError extends boolean = false>(options?: Options<AuthControllerLogoutData, ThrowOnError>) => (options?.client ?? client).post<AuthControllerLogoutResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/auth/logout',
    ...options
});

/**
 * Ask a question about the documents in a knowledge hub
 *
 * Asks a question in the single chat thread for this knowledge hub and returns an answer with sources.
 */
export const queryControllerQuery = <ThrowOnError extends boolean = false>(options: Options<QueryControllerQueryData, ThrowOnError>) => (options.client ?? client).post<QueryControllerQueryResponses, QueryControllerQueryErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/knowledge-hubs/{hubId}/chat/query',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get all messages in the knowledge hub chat thread
 */
export const chatMessagesControllerGetMessages = <ThrowOnError extends boolean = false>(options: Options<ChatMessagesControllerGetMessagesData, ThrowOnError>) => (options.client ?? client).get<ChatMessagesControllerGetMessagesResponses, ChatMessagesControllerGetMessagesErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/knowledge-hubs/{hubId}/chat/messages',
    ...options
});

/**
 * Delete a specific message from knowledge hub thread
 */
export const chatMessagesControllerDeleteMessage = <ThrowOnError extends boolean = false>(options: Options<ChatMessagesControllerDeleteMessageData, ThrowOnError>) => (options.client ?? client).delete<ChatMessagesControllerDeleteMessageResponses, ChatMessagesControllerDeleteMessageErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/knowledge-hubs/{hubId}/chat/messages/{messageId}',
    ...options
});
