// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { AppControllerGetHelloData, AppControllerGetHelloResponses, AuthControllerGoogleAuthData, AuthControllerLogoutData, AuthControllerLogoutResponses, AuthControllerMeData, AuthControllerMeErrors, AuthControllerMeResponses, AuthControllerRefreshData, AuthControllerRefreshErrors, AuthControllerRefreshResponses, ChatControllerClearHistoryData, ChatControllerClearHistoryErrors, ChatControllerClearHistoryResponses, ChatControllerDeleteMessageData, ChatControllerDeleteMessageErrors, ChatControllerDeleteMessageResponses, ChatControllerGetChatHistoryData, ChatControllerGetChatHistoryErrors, ChatControllerGetChatHistoryResponses, ChatControllerGetMessageData, ChatControllerGetMessageErrors, ChatControllerGetMessageResponses, ChatControllerQueryData, ChatControllerQueryErrors, ChatControllerQueryResponses, RagControllerDeleteFileData, RagControllerDeleteFileErrors, RagControllerDeleteFileResponses, RagControllerGetFileData, RagControllerGetFileErrors, RagControllerGetFileResponses, RagControllerGetFilesData, RagControllerGetFilesErrors, RagControllerGetFilesResponses, RagControllerIngestData, RagControllerIngestErrors, RagControllerIngestResponses, WorkspacesControllerCreateData, WorkspacesControllerCreateErrors, WorkspacesControllerCreateResponses, WorkspacesControllerFindAllData, WorkspacesControllerFindAllErrors, WorkspacesControllerFindAllResponses, WorkspacesControllerFindOneData, WorkspacesControllerFindOneErrors, WorkspacesControllerFindOneResponses, WorkspacesControllerRemoveData, WorkspacesControllerRemoveErrors, WorkspacesControllerRemoveResponses, WorkspacesControllerUpdateData, WorkspacesControllerUpdateErrors, WorkspacesControllerUpdateResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const appControllerGetHello = <ThrowOnError extends boolean = false>(options?: Options<AppControllerGetHelloData, ThrowOnError>) => (options?.client ?? client).get<AppControllerGetHelloResponses, unknown, ThrowOnError>({ url: '/', ...options });

/**
 * Get all files in a workspace
 */
export const ragControllerGetFiles = <ThrowOnError extends boolean = false>(options: Options<RagControllerGetFilesData, ThrowOnError>) => (options.client ?? client).get<RagControllerGetFilesResponses, RagControllerGetFilesErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/workspaces/{workspaceId}/files',
    ...options
});

/**
 * Upload and ingest a PDF file
 */
export const ragControllerIngest = <ThrowOnError extends boolean = false>(options: Options<RagControllerIngestData, ThrowOnError>) => (options.client ?? client).post<RagControllerIngestResponses, RagControllerIngestErrors, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/workspaces/{workspaceId}/files',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Delete a file
 */
export const ragControllerDeleteFile = <ThrowOnError extends boolean = false>(options: Options<RagControllerDeleteFileData, ThrowOnError>) => (options.client ?? client).delete<RagControllerDeleteFileResponses, RagControllerDeleteFileErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/workspaces/{workspaceId}/files/{fileId}',
    ...options
});

/**
 * Get a specific file by ID
 */
export const ragControllerGetFile = <ThrowOnError extends boolean = false>(options: Options<RagControllerGetFileData, ThrowOnError>) => (options.client ?? client).get<RagControllerGetFileResponses, RagControllerGetFileErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/workspaces/{workspaceId}/files/{fileId}',
    ...options
});

/**
 * Get all workspaces for the current user
 */
export const workspacesControllerFindAll = <ThrowOnError extends boolean = false>(options?: Options<WorkspacesControllerFindAllData, ThrowOnError>) => (options?.client ?? client).get<WorkspacesControllerFindAllResponses, WorkspacesControllerFindAllErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/workspaces',
    ...options
});

/**
 * Create a new workspace
 */
export const workspacesControllerCreate = <ThrowOnError extends boolean = false>(options: Options<WorkspacesControllerCreateData, ThrowOnError>) => (options.client ?? client).post<WorkspacesControllerCreateResponses, WorkspacesControllerCreateErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/workspaces',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a workspace
 */
export const workspacesControllerRemove = <ThrowOnError extends boolean = false>(options: Options<WorkspacesControllerRemoveData, ThrowOnError>) => (options.client ?? client).delete<WorkspacesControllerRemoveResponses, WorkspacesControllerRemoveErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/workspaces/{id}',
    ...options
});

/**
 * Get a specific workspace by ID
 */
export const workspacesControllerFindOne = <ThrowOnError extends boolean = false>(options: Options<WorkspacesControllerFindOneData, ThrowOnError>) => (options.client ?? client).get<WorkspacesControllerFindOneResponses, WorkspacesControllerFindOneErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/workspaces/{id}',
    ...options
});

/**
 * Update a workspace
 */
export const workspacesControllerUpdate = <ThrowOnError extends boolean = false>(options: Options<WorkspacesControllerUpdateData, ThrowOnError>) => (options.client ?? client).patch<WorkspacesControllerUpdateResponses, WorkspacesControllerUpdateErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/workspaces/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Initiate Google OAuth login
 */
export const authControllerGoogleAuth = <ThrowOnError extends boolean = false>(options?: Options<AuthControllerGoogleAuthData, ThrowOnError>) => (options?.client ?? client).get<unknown, unknown, ThrowOnError>({ url: '/auth/google', ...options });

/**
 * Get current authenticated user
 */
export const authControllerMe = <ThrowOnError extends boolean = false>(options?: Options<AuthControllerMeData, ThrowOnError>) => (options?.client ?? client).get<AuthControllerMeResponses, AuthControllerMeErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/auth/me',
    ...options
});

/**
 * Refresh access token using refresh token cookie
 */
export const authControllerRefresh = <ThrowOnError extends boolean = false>(options?: Options<AuthControllerRefreshData, ThrowOnError>) => (options?.client ?? client).post<AuthControllerRefreshResponses, AuthControllerRefreshErrors, ThrowOnError>({ url: '/auth/refresh', ...options });

/**
 * Logout and clear auth cookies
 */
export const authControllerLogout = <ThrowOnError extends boolean = false>(options?: Options<AuthControllerLogoutData, ThrowOnError>) => (options?.client ?? client).post<AuthControllerLogoutResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/auth/logout',
    ...options
});

/**
 * Ask a question about the documents in a workspace
 */
export const chatControllerQuery = <ThrowOnError extends boolean = false>(options: Options<ChatControllerQueryData, ThrowOnError>) => (options.client ?? client).post<ChatControllerQueryResponses, ChatControllerQueryErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/workspaces/{workspaceId}/chat/query',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Clear all chat history for a workspace
 */
export const chatControllerClearHistory = <ThrowOnError extends boolean = false>(options: Options<ChatControllerClearHistoryData, ThrowOnError>) => (options.client ?? client).delete<ChatControllerClearHistoryResponses, ChatControllerClearHistoryErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/workspaces/{workspaceId}/chat',
    ...options
});

/**
 * Get chat history for a workspace
 */
export const chatControllerGetChatHistory = <ThrowOnError extends boolean = false>(options: Options<ChatControllerGetChatHistoryData, ThrowOnError>) => (options.client ?? client).get<ChatControllerGetChatHistoryResponses, ChatControllerGetChatHistoryErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/workspaces/{workspaceId}/chat',
    ...options
});

/**
 * Delete a specific chat message
 */
export const chatControllerDeleteMessage = <ThrowOnError extends boolean = false>(options: Options<ChatControllerDeleteMessageData, ThrowOnError>) => (options.client ?? client).delete<ChatControllerDeleteMessageResponses, ChatControllerDeleteMessageErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/workspaces/{workspaceId}/chat/{messageId}',
    ...options
});

/**
 * Get a specific chat message
 */
export const chatControllerGetMessage = <ThrowOnError extends boolean = false>(options: Options<ChatControllerGetMessageData, ThrowOnError>) => (options.client ?? client).get<ChatControllerGetMessageResponses, ChatControllerGetMessageErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/workspaces/{workspaceId}/chat/{messageId}',
    ...options
});
