// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type FileResponseDto = {
    /**
     * File ID
     */
    id: string;
    /**
     * File name
     */
    name: string;
    /**
     * Original file name
     */
    originalName: string;
    /**
     * MIME type of the file
     */
    mimeType: string;
    /**
     * File size in bytes
     */
    size: number;
    /**
     * Processing status
     */
    status: 'pending' | 'processing' | 'completed' | 'failed';
    /**
     * Error message if processing failed
     */
    errorMessage?: string;
    /**
     * Workspace ID this file belongs to
     */
    workspaceId: string;
    /**
     * Created timestamp
     */
    createdAt: string;
    /**
     * Updated timestamp
     */
    updatedAt: string;
};

export type IngestResponseDto = {
    /**
     * Status message
     */
    message: string;
    /**
     * File ID
     */
    fileId: string;
    /**
     * Current processing status
     */
    status: 'pending' | 'processing' | 'completed' | 'failed';
};

export type CreateWorkspaceDto = {
    /**
     * Name of the workspace
     */
    name: string;
    /**
     * Optional description of the workspace
     */
    description?: string;
};

export type WorkspaceResponseDto = {
    /**
     * Unique identifier of the workspace
     */
    id: string;
    /**
     * Name of the workspace
     */
    name: string;
    /**
     * Description of the workspace
     */
    description: {
        [key: string]: unknown;
    } | null;
    /**
     * ID of the workspace owner
     */
    ownerId: string;
    /**
     * Creation timestamp
     */
    createdAt: string;
    /**
     * Last update timestamp
     */
    updatedAt: string;
};

export type UpdateWorkspaceDto = {
    /**
     * Name of the workspace
     */
    name?: string;
    /**
     * Optional description of the workspace
     */
    description?: string;
};

export type UserResponseDto = {
    /**
     * Unique identifier of the user
     */
    id: string;
    /**
     * Email address of the user
     */
    email: string;
    /**
     * First name of the user
     */
    firstName: {
        [key: string]: unknown;
    } | null;
    /**
     * Last name of the user
     */
    lastName: {
        [key: string]: unknown;
    } | null;
    /**
     * Profile picture URL
     */
    picture: {
        [key: string]: unknown;
    } | null;
    /**
     * Whether the user has admin privileges
     */
    isAdmin: boolean;
};

export type RefreshResponseDto = {
    /**
     * Indicates the refresh was successful
     */
    ok: boolean;
};

export type LogoutResponseDto = {
    /**
     * Indicates the logout was successful
     */
    ok: boolean;
};

export type QueryDto = {
    /**
     * The question to ask about the documents
     */
    question: string;
};

export type SourceDto = {
    /**
     * The file ID this chunk belongs to
     */
    fileId: string;
    /**
     * The text content of the chunk
     */
    text: string;
    /**
     * Similarity score (0-1)
     */
    score: number;
};

export type QueryResponseDto = {
    /**
     * The AI-generated answer
     */
    answer: string;
    /**
     * Source documents used to generate the answer
     */
    sources: Array<SourceDto>;
};

export type ChatMessageSourceDto = {
    /**
     * The file ID this source belongs to
     */
    fileId: string;
    /**
     * The text content of the source
     */
    text: string;
    /**
     * Similarity score (0-1)
     */
    score: number;
};

export type ChatMessageResponseDto = {
    /**
     * Unique identifier of the chat message
     */
    id: string;
    /**
     * The question asked by the user
     */
    question: string;
    /**
     * The AI-generated answer
     */
    answer: string;
    /**
     * Source documents used to generate the answer
     */
    sources: Array<ChatMessageSourceDto> | null;
    /**
     * ID of the workspace this message belongs to
     */
    workspaceId: string;
    /**
     * ID of the user who asked the question
     */
    userId: string;
    /**
     * When the message was created
     */
    createdAt: string;
};

export type ChatHistoryResponseDto = {
    /**
     * List of chat messages
     */
    messages: Array<ChatMessageResponseDto>;
    /**
     * Total number of messages
     */
    total: number;
};

export type AppControllerGetHelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type AppControllerGetHelloResponses = {
    200: unknown;
};

export type RagControllerGetFilesData = {
    body?: never;
    path: {
        /**
         * Workspace ID
         */
        workspaceId: string;
    };
    query?: never;
    url: '/workspaces/{workspaceId}/files';
};

export type RagControllerGetFilesErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Workspace not found
     */
    404: unknown;
};

export type RagControllerGetFilesResponses = {
    /**
     * List of files
     */
    200: Array<FileResponseDto>;
};

export type RagControllerGetFilesResponse = RagControllerGetFilesResponses[keyof RagControllerGetFilesResponses];

export type RagControllerIngestData = {
    body: {
        /**
         * PDF file to upload
         */
        file: Blob | File;
    };
    path: {
        /**
         * Workspace ID
         */
        workspaceId: string;
    };
    query?: never;
    url: '/workspaces/{workspaceId}/files';
};

export type RagControllerIngestErrors = {
    /**
     * Bad request - file is required or invalid file type
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Workspace not found
     */
    404: unknown;
};

export type RagControllerIngestResponses = {
    /**
     * File upload started
     */
    201: IngestResponseDto;
};

export type RagControllerIngestResponse = RagControllerIngestResponses[keyof RagControllerIngestResponses];

export type RagControllerDeleteFileData = {
    body?: never;
    path: {
        /**
         * File ID
         */
        fileId: string;
        /**
         * Workspace ID
         */
        workspaceId: string;
    };
    query?: never;
    url: '/workspaces/{workspaceId}/files/{fileId}';
};

export type RagControllerDeleteFileErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * File not found
     */
    404: unknown;
};

export type RagControllerDeleteFileResponses = {
    /**
     * File deleted successfully
     */
    200: unknown;
};

export type RagControllerGetFileData = {
    body?: never;
    path: {
        /**
         * File ID
         */
        fileId: string;
        /**
         * Workspace ID
         */
        workspaceId: string;
    };
    query?: never;
    url: '/workspaces/{workspaceId}/files/{fileId}';
};

export type RagControllerGetFileErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * File not found
     */
    404: unknown;
};

export type RagControllerGetFileResponses = {
    /**
     * File details
     */
    200: FileResponseDto;
};

export type RagControllerGetFileResponse = RagControllerGetFileResponses[keyof RagControllerGetFileResponses];

export type WorkspacesControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/workspaces';
};

export type WorkspacesControllerFindAllErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type WorkspacesControllerFindAllResponses = {
    /**
     * List of workspaces
     */
    200: Array<WorkspaceResponseDto>;
};

export type WorkspacesControllerFindAllResponse = WorkspacesControllerFindAllResponses[keyof WorkspacesControllerFindAllResponses];

export type WorkspacesControllerCreateData = {
    body: CreateWorkspaceDto;
    path?: never;
    query?: never;
    url: '/workspaces';
};

export type WorkspacesControllerCreateErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type WorkspacesControllerCreateResponses = {
    /**
     * Workspace created successfully
     */
    201: WorkspaceResponseDto;
};

export type WorkspacesControllerCreateResponse = WorkspacesControllerCreateResponses[keyof WorkspacesControllerCreateResponses];

export type WorkspacesControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/workspaces/{id}';
};

export type WorkspacesControllerRemoveErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Workspace not found
     */
    404: unknown;
};

export type WorkspacesControllerRemoveResponses = {
    /**
     * Workspace deleted successfully
     */
    200: unknown;
};

export type WorkspacesControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/workspaces/{id}';
};

export type WorkspacesControllerFindOneErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Workspace not found
     */
    404: unknown;
};

export type WorkspacesControllerFindOneResponses = {
    /**
     * Workspace details
     */
    200: WorkspaceResponseDto;
};

export type WorkspacesControllerFindOneResponse = WorkspacesControllerFindOneResponses[keyof WorkspacesControllerFindOneResponses];

export type WorkspacesControllerUpdateData = {
    body: UpdateWorkspaceDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/workspaces/{id}';
};

export type WorkspacesControllerUpdateErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Workspace not found
     */
    404: unknown;
};

export type WorkspacesControllerUpdateResponses = {
    /**
     * Workspace updated successfully
     */
    200: WorkspaceResponseDto;
};

export type WorkspacesControllerUpdateResponse = WorkspacesControllerUpdateResponses[keyof WorkspacesControllerUpdateResponses];

export type AuthControllerGoogleAuthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/google';
};

export type AuthControllerMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type AuthControllerMeErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type AuthControllerMeResponses = {
    /**
     * Current user profile
     */
    200: UserResponseDto;
};

export type AuthControllerMeResponse = AuthControllerMeResponses[keyof AuthControllerMeResponses];

export type AuthControllerRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type AuthControllerRefreshErrors = {
    /**
     * Invalid or missing refresh token
     */
    401: unknown;
};

export type AuthControllerRefreshResponses = {
    /**
     * Tokens refreshed successfully
     */
    200: RefreshResponseDto;
};

export type AuthControllerRefreshResponse = AuthControllerRefreshResponses[keyof AuthControllerRefreshResponses];

export type AuthControllerLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type AuthControllerLogoutResponses = {
    /**
     * Logged out successfully
     */
    200: LogoutResponseDto;
};

export type AuthControllerLogoutResponse = AuthControllerLogoutResponses[keyof AuthControllerLogoutResponses];

export type ChatControllerQueryData = {
    body: QueryDto;
    path: {
        /**
         * Workspace ID
         */
        workspaceId: string;
    };
    query?: never;
    url: '/workspaces/{workspaceId}/chat/query';
};

export type ChatControllerQueryErrors = {
    /**
     * Bad request - no processed documents in workspace
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Workspace not found
     */
    404: unknown;
};

export type ChatControllerQueryResponses = {
    /**
     * AI-generated answer with sources
     */
    200: QueryResponseDto;
};

export type ChatControllerQueryResponse = ChatControllerQueryResponses[keyof ChatControllerQueryResponses];

export type ChatControllerClearHistoryData = {
    body?: never;
    path: {
        /**
         * Workspace ID
         */
        workspaceId: string;
    };
    query?: never;
    url: '/workspaces/{workspaceId}/chat';
};

export type ChatControllerClearHistoryErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type ChatControllerClearHistoryResponses = {
    /**
     * Chat history cleared successfully
     */
    200: unknown;
};

export type ChatControllerGetChatHistoryData = {
    body?: never;
    path: {
        /**
         * Workspace ID
         */
        workspaceId: string;
    };
    query?: {
        /**
         * Number of messages to return (default: 50)
         */
        limit?: number;
        /**
         * Number of messages to skip (default: 0)
         */
        offset?: number;
    };
    url: '/workspaces/{workspaceId}/chat';
};

export type ChatControllerGetChatHistoryErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Workspace not found
     */
    404: unknown;
};

export type ChatControllerGetChatHistoryResponses = {
    /**
     * Chat history retrieved successfully
     */
    200: ChatHistoryResponseDto;
};

export type ChatControllerGetChatHistoryResponse = ChatControllerGetChatHistoryResponses[keyof ChatControllerGetChatHistoryResponses];

export type ChatControllerDeleteMessageData = {
    body?: never;
    path: {
        /**
         * Message ID
         */
        messageId: string;
        /**
         * Workspace ID
         */
        workspaceId: string;
    };
    query?: never;
    url: '/workspaces/{workspaceId}/chat/{messageId}';
};

export type ChatControllerDeleteMessageErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Message not found
     */
    404: unknown;
};

export type ChatControllerDeleteMessageResponses = {
    /**
     * Message deleted successfully
     */
    200: unknown;
};

export type ChatControllerGetMessageData = {
    body?: never;
    path: {
        /**
         * Message ID
         */
        messageId: string;
        /**
         * Workspace ID
         */
        workspaceId: string;
    };
    query?: never;
    url: '/workspaces/{workspaceId}/chat/{messageId}';
};

export type ChatControllerGetMessageErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Message not found
     */
    404: unknown;
};

export type ChatControllerGetMessageResponses = {
    /**
     * Chat message retrieved successfully
     */
    200: ChatMessageResponseDto;
};

export type ChatControllerGetMessageResponse = ChatControllerGetMessageResponses[keyof ChatControllerGetMessageResponses];
