// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type FileResponseDto = {
    id: string;
    name: string;
};

export type AppControllerGetHelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type AppControllerGetHelloResponses = {
    200: unknown;
};

export type RagControllerGetFilesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/rag/files';
};

export type RagControllerGetFilesResponses = {
    default: Array<FileResponseDto>;
};

export type RagControllerGetFilesResponse = RagControllerGetFilesResponses[keyof RagControllerGetFilesResponses];

export type RagControllerIngestData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/rag/ingest';
};

export type RagControllerIngestResponses = {
    201: unknown;
};

export type AuthControllerGoogleAuthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/google';
};

export type AuthControllerGoogleAuthResponses = {
    200: unknown;
};

export type AuthControllerGoogleAuthRedirectData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/google/callback';
};

export type AuthControllerGoogleAuthRedirectResponses = {
    200: unknown;
};
