// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type FileResponseDto = {
    /**
     * File ID
     */
    id: string;
    /**
     * File name
     */
    name: string;
    /**
     * Original file name
     */
    originalName: string;
    /**
     * MIME type of the file
     */
    mimeType: string;
    /**
     * File size in bytes
     */
    size: number;
    /**
     * Processing status
     */
    status: 'pending' | 'processing' | 'completed' | 'failed';
    /**
     * Error message if processing failed
     */
    errorMessage?: string;
    /**
     * Knowledge hub ID this file belongs to
     */
    knowledgeHubId: string;
    /**
     * Created timestamp
     */
    createdAt: string;
    /**
     * Updated timestamp
     */
    updatedAt: string;
};

export type IngestResponseDto = {
    /**
     * Status message
     */
    message: string;
    /**
     * File ID
     */
    fileId: string;
    /**
     * Current processing status
     */
    status: 'pending' | 'processing' | 'completed' | 'failed';
};

export type CreateKnowledgeHubDto = {
    /**
     * Name of the knowledge hub
     */
    name: string;
    /**
     * Optional description of the knowledge hub
     */
    description?: string;
};

export type KnowledgeHubResponseDto = {
    /**
     * Unique identifier of the knowledge hub
     */
    id: string;
    /**
     * Name of the knowledge hub
     */
    name: string;
    /**
     * Description of the knowledge hub
     */
    description: {
        [key: string]: unknown;
    } | null;
    /**
     * ID of the knowledge hub owner
     */
    ownerId: string;
    /**
     * Creation timestamp
     */
    createdAt: string;
    /**
     * Last update timestamp
     */
    updatedAt: string;
};

export type UpdateKnowledgeHubDto = {
    /**
     * Name of the knowledge hub
     */
    name?: string;
    /**
     * Optional description of the knowledge hub
     */
    description?: string;
};

export type UserResponseDto = {
    /**
     * Unique identifier of the user
     */
    id: string;
    /**
     * Email address of the user
     */
    email: string;
    /**
     * First name of the user
     */
    firstName: {
        [key: string]: unknown;
    } | null;
    /**
     * Last name of the user
     */
    lastName: {
        [key: string]: unknown;
    } | null;
    /**
     * Profile picture URL
     */
    picture: {
        [key: string]: unknown;
    } | null;
    /**
     * Whether the user has admin privileges
     */
    isAdmin: boolean;
};

export type RefreshResponseDto = {
    /**
     * Indicates the refresh was successful
     */
    ok: boolean;
};

export type LogoutResponseDto = {
    /**
     * Indicates the logout was successful
     */
    ok: boolean;
};

export type QueryInConversationDto = {
    /**
     * The question to ask about the documents
     */
    question: string;
    /**
     * ID of an existing conversation to continue. If not provided, a new conversation will be created.
     */
    conversationId?: string;
};

export type QueryInConversationResponseDto = {
    /**
     * The AI-generated answer
     */
    answer: string;
    /**
     * Source documents used to generate the answer
     */
    sources: Array<{
        fileId?: string;
        text?: string;
        score?: number;
    }>;
    /**
     * The conversation ID (new or existing)
     */
    conversationId: string;
    /**
     * The message ID of this Q&A
     */
    messageId: string;
};

export type ChatMessageSourceDto = {
    /**
     * The file ID this source belongs to
     */
    fileId: string;
    /**
     * The text content of the source
     */
    text: string;
    /**
     * Similarity score (0-1)
     */
    score: number;
};

export type ChatMessageResponseDto = {
    /**
     * Unique identifier of the chat message
     */
    id: string;
    /**
     * The question asked by the user
     */
    question: string;
    /**
     * The AI-generated answer
     */
    answer: string;
    /**
     * Source documents used to generate the answer
     */
    sources: Array<ChatMessageSourceDto> | null;
    /**
     * ID of the thread this message belongs to
     */
    threadId: string;
    /**
     * ID of the user who asked the question
     */
    userId: string;
    /**
     * When the message was created
     */
    createdAt: string;
};

export type CreateNoteDto = {
    /**
     * Note title
     */
    title: string;
    /**
     * Note content in plain text or markdown
     */
    content: string;
};

export type UpdateNoteDto = {
    /**
     * Note title
     */
    title?: string;
    /**
     * Note content in plain text or markdown
     */
    content?: string;
};

export type GenerateNoteDto = {
    /**
     * How the note should be generated
     */
    mode: 'from_answer' | 'from_selection' | 'from_topic_query';
    /**
     * Topic query text used when mode is from_topic_query
     */
    query?: string;
    /**
     * Chat message ID used when mode is from_answer
     */
    messageId?: string;
    /**
     * Document ID used when mode is from_selection
     */
    documentId?: string;
    /**
     * Selected text from document used when mode is from_selection
     */
    selectionText?: string;
    /**
     * Optional note title override
     */
    title?: string;
};

export type CreateFlashcardDto = {
    /**
     * Flashcard front text (question/prompt)
     */
    front: string;
    /**
     * Flashcard back text (answer/explanation)
     */
    back: string;
};

export type UpdateFlashcardDto = {
    /**
     * Flashcard front text (question/prompt)
     */
    front?: string;
    /**
     * Flashcard back text (answer/explanation)
     */
    back?: string;
};

export type GenerateFlashcardDto = {
    /**
     * How the flashcards should be generated
     */
    mode: 'from_answer' | 'from_selection' | 'from_topic_query';
    /**
     * Topic query text used when mode is from_topic_query
     */
    query?: string;
    /**
     * Chat message ID used when mode is from_answer
     */
    messageId?: string;
    /**
     * Document ID used when mode is from_selection
     */
    documentId?: string;
    /**
     * Selected text from document used when mode is from_selection
     */
    selectionText?: string;
    /**
     * Number of flashcards to generate
     */
    count?: number;
};

export type DocumentsControllerGetFilesData = {
    body?: never;
    path: {
        /**
         * Knowledge Hub ID
         */
        hubId: string;
    };
    query?: never;
    url: '/knowledge-hubs/{hubId}/documents';
};

export type DocumentsControllerGetFilesResponses = {
    /**
     * List of documents
     */
    200: Array<FileResponseDto>;
};

export type DocumentsControllerGetFilesResponse = DocumentsControllerGetFilesResponses[keyof DocumentsControllerGetFilesResponses];

export type DocumentsControllerIngestData = {
    body: {
        /**
         * PDF document to upload
         */
        file: Blob | File;
    };
    path: {
        /**
         * Knowledge Hub ID
         */
        hubId: string;
    };
    query?: never;
    url: '/knowledge-hubs/{hubId}/documents';
};

export type DocumentsControllerIngestResponses = {
    /**
     * Document upload started
     */
    201: IngestResponseDto;
};

export type DocumentsControllerIngestResponse = DocumentsControllerIngestResponses[keyof DocumentsControllerIngestResponses];

export type DocumentsControllerDeleteFileData = {
    body?: never;
    path: {
        /**
         * Document ID
         */
        fileId: string;
        /**
         * Knowledge Hub ID
         */
        hubId: string;
    };
    query?: never;
    url: '/knowledge-hubs/{hubId}/documents/{fileId}';
};

export type DocumentsControllerDeleteFileResponses = {
    200: unknown;
};

export type DocumentsControllerGetFileData = {
    body?: never;
    path: {
        /**
         * Document ID
         */
        fileId: string;
        /**
         * Knowledge Hub ID
         */
        hubId: string;
    };
    query?: never;
    url: '/knowledge-hubs/{hubId}/documents/{fileId}';
};

export type DocumentsControllerGetFileResponses = {
    /**
     * Document details
     */
    200: FileResponseDto;
};

export type DocumentsControllerGetFileResponse = DocumentsControllerGetFileResponses[keyof DocumentsControllerGetFileResponses];

export type KnowledgeHubsControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/knowledge-hubs';
};

export type KnowledgeHubsControllerFindAllErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type KnowledgeHubsControllerFindAllResponses = {
    /**
     * List of knowledge hubs
     */
    200: Array<KnowledgeHubResponseDto>;
};

export type KnowledgeHubsControllerFindAllResponse = KnowledgeHubsControllerFindAllResponses[keyof KnowledgeHubsControllerFindAllResponses];

export type KnowledgeHubsControllerCreateData = {
    body: CreateKnowledgeHubDto;
    path?: never;
    query?: never;
    url: '/knowledge-hubs';
};

export type KnowledgeHubsControllerCreateErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type KnowledgeHubsControllerCreateResponses = {
    /**
     * Knowledge hub created successfully
     */
    201: KnowledgeHubResponseDto;
};

export type KnowledgeHubsControllerCreateResponse = KnowledgeHubsControllerCreateResponses[keyof KnowledgeHubsControllerCreateResponses];

export type KnowledgeHubsControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/knowledge-hubs/{id}';
};

export type KnowledgeHubsControllerRemoveErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Knowledge hub not found
     */
    404: unknown;
};

export type KnowledgeHubsControllerRemoveResponses = {
    /**
     * Knowledge hub deleted successfully
     */
    200: unknown;
};

export type KnowledgeHubsControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/knowledge-hubs/{id}';
};

export type KnowledgeHubsControllerFindOneErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Knowledge hub not found
     */
    404: unknown;
};

export type KnowledgeHubsControllerFindOneResponses = {
    /**
     * Knowledge hub details
     */
    200: KnowledgeHubResponseDto;
};

export type KnowledgeHubsControllerFindOneResponse = KnowledgeHubsControllerFindOneResponses[keyof KnowledgeHubsControllerFindOneResponses];

export type KnowledgeHubsControllerUpdateData = {
    body: UpdateKnowledgeHubDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/knowledge-hubs/{id}';
};

export type KnowledgeHubsControllerUpdateErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Knowledge hub not found
     */
    404: unknown;
};

export type KnowledgeHubsControllerUpdateResponses = {
    /**
     * Knowledge hub updated successfully
     */
    200: KnowledgeHubResponseDto;
};

export type KnowledgeHubsControllerUpdateResponse = KnowledgeHubsControllerUpdateResponses[keyof KnowledgeHubsControllerUpdateResponses];

export type AuthControllerGoogleAuthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/google';
};

export type AuthControllerMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type AuthControllerMeErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type AuthControllerMeResponses = {
    /**
     * Current user profile
     */
    200: UserResponseDto;
};

export type AuthControllerMeResponse = AuthControllerMeResponses[keyof AuthControllerMeResponses];

export type AuthControllerRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type AuthControllerRefreshErrors = {
    /**
     * Invalid or missing refresh token
     */
    401: unknown;
};

export type AuthControllerRefreshResponses = {
    /**
     * Tokens refreshed successfully
     */
    200: RefreshResponseDto;
};

export type AuthControllerRefreshResponse = AuthControllerRefreshResponses[keyof AuthControllerRefreshResponses];

export type AuthControllerLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type AuthControllerLogoutResponses = {
    /**
     * Logged out successfully
     */
    200: LogoutResponseDto;
};

export type AuthControllerLogoutResponse = AuthControllerLogoutResponses[keyof AuthControllerLogoutResponses];

export type QueryControllerQueryData = {
    body: QueryInConversationDto;
    path: {
        /**
         * Knowledge Hub ID
         */
        hubId: string;
    };
    query?: never;
    url: '/knowledge-hubs/{hubId}/chat/query';
};

export type QueryControllerQueryErrors = {
    /**
     * Bad request - no processed documents in knowledge hub
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Knowledge hub thread not found
     */
    404: unknown;
};

export type QueryControllerQueryResponses = {
    /**
     * AI-generated answer with sources
     */
    200: QueryInConversationResponseDto;
};

export type QueryControllerQueryResponse = QueryControllerQueryResponses[keyof QueryControllerQueryResponses];

export type ConversationsControllerGetMessagesData = {
    body?: never;
    path: {
        /**
         * Knowledge Hub ID
         */
        hubId: string;
    };
    query?: never;
    url: '/knowledge-hubs/{hubId}/chat/messages';
};

export type ConversationsControllerGetMessagesErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type ConversationsControllerGetMessagesResponses = {
    /**
     * List of messages in the knowledge hub chat thread
     */
    200: Array<ChatMessageResponseDto>;
};

export type ConversationsControllerGetMessagesResponse = ConversationsControllerGetMessagesResponses[keyof ConversationsControllerGetMessagesResponses];

export type ConversationsControllerDeleteMessageData = {
    body?: never;
    path: {
        /**
         * Message ID
         */
        messageId: string;
        /**
         * Knowledge Hub ID
         */
        hubId: string;
    };
    query?: never;
    url: '/knowledge-hubs/{hubId}/chat/messages/{messageId}';
};

export type ConversationsControllerDeleteMessageErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Message not found
     */
    404: unknown;
};

export type ConversationsControllerDeleteMessageResponses = {
    /**
     * Message deleted successfully
     */
    200: unknown;
};

export type NotesControllerFindAllData = {
    body?: never;
    path: {
        /**
         * Knowledge Hub ID
         */
        hubId: string;
    };
    query?: never;
    url: '/knowledge-hubs/{hubId}/notes';
};

export type NotesControllerFindAllErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type NotesControllerFindAllResponses = {
    /**
     * Notes list
     */
    200: unknown;
};

export type NotesControllerCreateData = {
    body: CreateNoteDto;
    path: {
        /**
         * Knowledge Hub ID
         */
        hubId: string;
    };
    query?: never;
    url: '/knowledge-hubs/{hubId}/notes';
};

export type NotesControllerCreateErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type NotesControllerCreateResponses = {
    /**
     * Note created successfully
     */
    201: unknown;
};

export type NotesControllerRemoveData = {
    body?: never;
    path: {
        noteId: string;
        /**
         * Knowledge Hub ID
         */
        hubId: string;
    };
    query?: never;
    url: '/knowledge-hubs/{hubId}/notes/{noteId}';
};

export type NotesControllerRemoveErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Note not found
     */
    404: unknown;
};

export type NotesControllerRemoveResponses = {
    /**
     * Note deleted successfully
     */
    200: unknown;
};

export type NotesControllerFindOneData = {
    body?: never;
    path: {
        noteId: string;
        /**
         * Knowledge Hub ID
         */
        hubId: string;
    };
    query?: never;
    url: '/knowledge-hubs/{hubId}/notes/{noteId}';
};

export type NotesControllerFindOneErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Note not found
     */
    404: unknown;
};

export type NotesControllerFindOneResponses = {
    /**
     * Note details
     */
    200: unknown;
};

export type NotesControllerUpdateData = {
    body: UpdateNoteDto;
    path: {
        noteId: string;
        /**
         * Knowledge Hub ID
         */
        hubId: string;
    };
    query?: never;
    url: '/knowledge-hubs/{hubId}/notes/{noteId}';
};

export type NotesControllerUpdateErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Note not found
     */
    404: unknown;
};

export type NotesControllerUpdateResponses = {
    /**
     * Note updated successfully
     */
    200: unknown;
};

export type NotesControllerGenerateData = {
    body: GenerateNoteDto;
    path: {
        /**
         * Knowledge Hub ID
         */
        hubId: string;
    };
    query?: never;
    url: '/knowledge-hubs/{hubId}/notes/generate';
};

export type NotesControllerGenerateErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type NotesControllerGenerateResponses = {
    /**
     * Note generated successfully
     */
    201: unknown;
};

export type FlashcardsControllerFindAllData = {
    body?: never;
    path: {
        /**
         * Knowledge Hub ID
         */
        hubId: string;
    };
    query?: never;
    url: '/knowledge-hubs/{hubId}/flashcards';
};

export type FlashcardsControllerFindAllErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type FlashcardsControllerFindAllResponses = {
    /**
     * Flashcards list
     */
    200: unknown;
};

export type FlashcardsControllerCreateData = {
    body: CreateFlashcardDto;
    path: {
        /**
         * Knowledge Hub ID
         */
        hubId: string;
    };
    query?: never;
    url: '/knowledge-hubs/{hubId}/flashcards';
};

export type FlashcardsControllerCreateErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type FlashcardsControllerCreateResponses = {
    /**
     * Flashcard created successfully
     */
    201: unknown;
};

export type FlashcardsControllerRemoveData = {
    body?: never;
    path: {
        flashcardId: string;
        /**
         * Knowledge Hub ID
         */
        hubId: string;
    };
    query?: never;
    url: '/knowledge-hubs/{hubId}/flashcards/{flashcardId}';
};

export type FlashcardsControllerRemoveErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Flashcard not found
     */
    404: unknown;
};

export type FlashcardsControllerRemoveResponses = {
    /**
     * Flashcard deleted successfully
     */
    200: unknown;
};

export type FlashcardsControllerFindOneData = {
    body?: never;
    path: {
        flashcardId: string;
        /**
         * Knowledge Hub ID
         */
        hubId: string;
    };
    query?: never;
    url: '/knowledge-hubs/{hubId}/flashcards/{flashcardId}';
};

export type FlashcardsControllerFindOneErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Flashcard not found
     */
    404: unknown;
};

export type FlashcardsControllerFindOneResponses = {
    /**
     * Flashcard details
     */
    200: unknown;
};

export type FlashcardsControllerUpdateData = {
    body: UpdateFlashcardDto;
    path: {
        flashcardId: string;
        /**
         * Knowledge Hub ID
         */
        hubId: string;
    };
    query?: never;
    url: '/knowledge-hubs/{hubId}/flashcards/{flashcardId}';
};

export type FlashcardsControllerUpdateErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Flashcard not found
     */
    404: unknown;
};

export type FlashcardsControllerUpdateResponses = {
    /**
     * Flashcard updated successfully
     */
    200: unknown;
};

export type FlashcardsControllerGenerateData = {
    body: GenerateFlashcardDto;
    path: {
        /**
         * Knowledge Hub ID
         */
        hubId: string;
    };
    query?: never;
    url: '/knowledge-hubs/{hubId}/flashcards/generate';
};

export type FlashcardsControllerGenerateErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type FlashcardsControllerGenerateResponses = {
    /**
     * Flashcards generated successfully
     */
    201: unknown;
};
